#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC7125C934883BE5 (me@adamj.eu)
#
Name     : pytest-randomly
Version  : 3.1.0
Release  : 9
URL      : https://files.pythonhosted.org/packages/34/3c/b7f3ebf4b673be9d8a8488af093f36c7392bd87d0d897127e8cb096ff625/pytest-randomly-3.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/34/3c/b7f3ebf4b673be9d8a8488af093f36c7392bd87d0d897127e8cb096ff625/pytest-randomly-3.1.0.tar.gz
Source1 : https://files.pythonhosted.org/packages/34/3c/b7f3ebf4b673be9d8a8488af093f36c7392bd87d0d897127e8cb096ff625/pytest-randomly-3.1.0.tar.gz.asc
Summary  : Pytest plugin to randomly order tests and control random.seed.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pytest-randomly-license = %{version}-%{release}
Requires: pytest-randomly-python = %{version}-%{release}
Requires: pytest-randomly-python3 = %{version}-%{release}
Requires: entrypoints
Requires: pytest
BuildRequires : buildreq-distutils3
BuildRequires : entrypoints
BuildRequires : pytest

%description
===============
pytest-randomly
===============
.. image:: https://img.shields.io/travis/pytest-dev/pytest-randomly.svg
:target: https://travis-ci.org/pytest-dev/pytest-randomly

%package license
Summary: license components for the pytest-randomly package.
Group: Default

%description license
license components for the pytest-randomly package.


%package python
Summary: python components for the pytest-randomly package.
Group: Default
Requires: pytest-randomly-python3 = %{version}-%{release}

%description python
python components for the pytest-randomly package.


%package python3
Summary: python3 components for the pytest-randomly package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytest-randomly package.


%prep
%setup -q -n pytest-randomly-3.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566838459
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-randomly
cp LICENSE %{buildroot}/usr/share/package-licenses/pytest-randomly/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-randomly/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
