#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-randomly
Version  : 3.10.1
Release  : 34
URL      : https://files.pythonhosted.org/packages/54/64/ce9faed238e68243b7bd4caf8f1b261a82a28651878fcd01f98dd9555364/pytest-randomly-3.10.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/54/64/ce9faed238e68243b7bd4caf8f1b261a82a28651878fcd01f98dd9555364/pytest-randomly-3.10.1.tar.gz
Summary  : Pytest plugin to randomly order tests and control random.seed.
Group    : Development/Tools
License  : MIT
Requires: pytest-randomly-license = %{version}-%{release}
Requires: pytest-randomly-python = %{version}-%{release}
Requires: pytest-randomly-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
===============
pytest-randomly
===============
.. image:: https://img.shields.io/github/workflow/status/pytest-dev/pytest-randomly/CI/main?style=for-the-badge
:target: https://github.com/pytest-dev/pytest-randomly/actions?workflow=CI

%package license
Summary: license components for the pytest-randomly package.
Group: Default

%description license
license components for the pytest-randomly package.


%package python
Summary: python components for the pytest-randomly package.
Group: Default
Requires: pytest-randomly-python3 = %{version}-%{release}

%description python
python components for the pytest-randomly package.


%package python3
Summary: python3 components for the pytest-randomly package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_randomly)
Requires: pypi(importlib_metadata)
Requires: pypi(pytest)

%description python3
python3 components for the pytest-randomly package.


%prep
%setup -q -n pytest-randomly-3.10.1
cd %{_builddir}/pytest-randomly-3.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629132322
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-randomly
cp %{_builddir}/pytest-randomly-3.10.1/LICENSE %{buildroot}/usr/share/package-licenses/pytest-randomly/357dd8dc959a96d3bc13e11e940ccc7dd955492b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-randomly/357dd8dc959a96d3bc13e11e940ccc7dd955492b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
