#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC7125C934883BE5 (me@adamj.eu)
#
Name     : pytest-randomly
Version  : 3.8.0
Release  : 31
URL      : https://files.pythonhosted.org/packages/e6/04/8d27d8a439c4499d68355a7aa7121f3b315812157bc180ed7646fde9d89b/pytest-randomly-3.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e6/04/8d27d8a439c4499d68355a7aa7121f3b315812157bc180ed7646fde9d89b/pytest-randomly-3.8.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/e6/04/8d27d8a439c4499d68355a7aa7121f3b315812157bc180ed7646fde9d89b/pytest-randomly-3.8.0.tar.gz.asc
Summary  : Pytest plugin to randomly order tests and control random.seed.
Group    : Development/Tools
License  : MIT
Requires: pytest-randomly-license = %{version}-%{release}
Requires: pytest-randomly-python = %{version}-%{release}
Requires: pytest-randomly-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
pytest-randomly
        ===============

%package license
Summary: license components for the pytest-randomly package.
Group: Default

%description license
license components for the pytest-randomly package.


%package python
Summary: python components for the pytest-randomly package.
Group: Default
Requires: pytest-randomly-python3 = %{version}-%{release}

%description python
python components for the pytest-randomly package.


%package python3
Summary: python3 components for the pytest-randomly package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_randomly)
Requires: pypi(importlib_metadata)
Requires: pypi(pytest)

%description python3
python3 components for the pytest-randomly package.


%prep
%setup -q -n pytest-randomly-3.8.0
cd %{_builddir}/pytest-randomly-3.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620660187
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-randomly
cp %{_builddir}/pytest-randomly-3.8.0/LICENSE %{buildroot}/usr/share/package-licenses/pytest-randomly/357dd8dc959a96d3bc13e11e940ccc7dd955492b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-randomly/357dd8dc959a96d3bc13e11e940ccc7dd955492b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
